version: '3'
services:
  mysql:
    container_name: note-mysql
    build:
      context: ./db
      dockerfile: dev.Dockerfile
    env_file: ./.env
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "7152:3306"
    networks:
      - note
  
  phpmyadmin:
    container_name: note-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 7153:80
    env_file: ./.env
    depends_on:
      - mysql
    networks:
      - note

  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    env_file: ./.env
    volumes:
      - ./client:/app
    ports:
      - 7150:3000
    networks:
      - note
    tty: true

volumes:
  mysql:

networks:
  note:
    driver: bridge