export const logsActions = {
  GET_LOGS: "GET_LOGS",
  GET_LOGS_SUCCESS: "GET_LOGS_SUCCESS",
  GET_LOGS_ERROR: "GET_LOGS_ERROR",
  CREATE_LOG: "CREATE_LOG",
  CREATE_LOG_SUCCESS: "CREATE_LOG_SUCCESS",
  CREATE_LOG_ERROR: "CREATE_LOG_ERROR",
  UPDATE_LOGS: "UPDATE_LOGS",
  UPDATE_LOGS_SUCCESS: "UPDATE_LOGS_SUCCESS",
  UPDATE_LOGS_ERROR: "UPDATE_LOGS_ERROR",
  DELETE_LOGS: "DELETE_LOGS",
  DELETE_LOGS_SUCCESS: "DELETE_LOGS_SUCCESS",
  DELETE_LOGS_ERROR: "DELETE_LOGS_ERROR"
}