export const papersDetailActions = {
  GET_PAPER_DETAILS: "GET_PAPER_DETAILS",
  GET_PAPER_DETAILS_SUCCESS: "GET_PAPER_DETAILS_SUCCESS",
  GET_PAPER_DETAILS_ERROR: "GET_PAPER_DETAILS_ERROR",
  CREATE_PAPER_DETAIL: "CREATE_PAPER_DETAIL",
  CREATE_PAPER_DETAIL_SUCCESS: "CREATE_PAPER_DETAIL_SUCCESS",
  CREATE_PAPER_DETAIL_ERROR: "CREATE_PAPER_DETAIL_ERROR",
}