export const papersActions = {
  GET_PAPERS: "GET_PAPERS",
  GET_PAPERS_SUCCESS: "GET_PAPERS_SUCCESS",
  GET_PAPERS_ERROR: "GET_PAPERS_ERROR",
  CREATE_PAPER: "CREATE_PAPER",
  CREATE_PAPER_SUCCESS: "CREATE_PAPER_SUCCESS",
  CREATE_PAPER_ERROR: "CREATE_PAPER_ERROR",
  DELETE_PAPER: "DELETE_PAPER",
  DELETE_PAPER_SUCCESS: "DELETE_PAPER_SUCCESS",
  DELETE_PAPER_ERROR: "DELETE_PAPER_ERROR",
}