export const strokesActions = {
  GET_STROKES: "GET_STROKES",
  GET_STROKES_SUCCESS: "GET_STROKES_SUCCESS",
  GET_STROKES_ERROR: "GET_STROKES_ERROR",
  CREATE_STROKE: "CREATE_STROKE",
  CREATE_STROKE_SUCCESS: "CREATE_STROKE_SUCCESS",
  CREATE_STROKE_ERROR: "CREATE_STROKE_ERROR",
  DELETE_STROKES: "DELETE_STROKES",
  DELETE_STROKES_SUCCESS: "DELETE_STROKES_SUCCESS",
  DELETE_STROKES_ERROR: "DELETE_STROKES_ERROR"
}