export const usePressureUndoActions = {
  CREATE_USE_PRESSURE_UNDO: "CREATE_USE_PRESSURE_UNDO",
  CREATE_USE_PRESSURE_UNDO_SUCCESS: "CREATE_USE_PRESSURE_UNDO_SUCCESS",
  CREATE_USE_PRESSURE_UNDO_ERROR: "CREATE_USE_PRESSURE_UNDO_ERROR"
}