export const usersActions = {
  GET_ALL_EXAM_USERS: "GET_ALL_EXAM_USERS",
  GET_ALL_EXAM_USERS_SUCCESS: "GET_ALL_EXAM_USERS_SUCCESS",
  GET_ALL_EXAM_USERS_ERROR: "GET_ALL_EXAM_USERS_ERROR",
  CREATE_EXAM_USER: "CREATE_EXAM_USER",
  CREATE_EXAM_USER_SUCCESS: "CREATE_EXAM_USER_SUCCESS",
  CREATE_EXAM_USER_ERROR: "CREATE_EXAM_USER_ERROR",
}